import asyncio
import json
import os
from collections.abc import Mapping
from typing import Any

import ollama
from fastmcp import Client
from fastmcp.client.transports import StdioTransport
from mcp.types import TextContent

MODEL = os.getenv("OLLAMA_MODEL", "qwen3.5:4b-mlx")

SERVER_ENV_VARS = ("TASK_BACKEND", "DB_PATH")


def server_env() -> dict[str, str]:
    """The MCP SDK only inherits a whitelist of variables; ours must be passed explicitly."""
    return {k: v for k in SERVER_ENV_VARS if (v := os.getenv(k)) is not None}


def mcp_tools_to_ollama(mcp_tools):
    """Converts MCP tools to Ollama tool format."""
    return [
        {
            "type": "function",
            "function": {
                "name": tool.name,
                "description": tool.description or "",
                "parameters": tool.input_schema or {"type": "object", "properties": {}},
            },
        }
        for tool in mcp_tools
    ]


def normalize_args(args: Mapping[str, Any]) -> dict[str, Any]:
    """Fixes malformed arguments generated by some Ollama models that leak
    the JSON schema into values (e.g. {'type': 'string', 'value': '...'})."""
    normalized = {}
    for key, value in args.items():
        if isinstance(value, dict) and "value" in value:
            normalized[key] = value["value"]
        else:
            normalized[key] = value
    return normalized


def sanitize_args(name: str, args: dict[str, Any], tools_by_name: dict) -> dict[str, Any]:
    """Removes arguments not declared in the tool's input schema,
    to handle hallucinated parameters from poorly-behaving models."""
    tool = tools_by_name.get(name)
    if not tool or not tool.input_schema:
        return args
    known_keys = set(tool.input_schema.get("properties", {}).keys())
    return {k: v for k, v in args.items() if k in known_keys}


async def run():
    """Main loop to interact with the user and call MCP tools via Ollama."""
    async with Client(StdioTransport("uv", ["run", "mcpserver-template"], env=server_env())) as mcp:
        # Connect to the MCP server
        mcp_tools = await mcp.list_tools()
        ollama_tools = mcp_tools_to_ollama(mcp_tools)
        tools_by_name = {tool.name: tool for tool in mcp_tools}

        print(f"✅ Serveur MCP connecté — {len(mcp_tools)} outils disponibles")
        print(f"🤖 Modèle : {MODEL}\n")

        messages: list[Any] = [
            {
                "role": "system",
                "content": (
                    "Tu es un assistant de gestion de tâches. "
                    "Utilise les outils disponibles pour répondre aux demandes de l'utilisateur."
                ),
            }
        ]

        # and start the interactive loop
        while True:
            try:
                user_input = input("Vous : ").strip()
            except (KeyboardInterrupt, EOFError):
                print("\nAu revoir !")
                break

            if not user_input or user_input.lower() in ("exit", "quit"):
                break

            messages.append({"role": "user", "content": user_input})

            # Tools calls loop
            while True:
                response = ollama.chat(
                    model=MODEL,
                    messages=messages,
                    tools=ollama_tools,
                )
                msg = response.message

                if not msg.tool_calls:
                    # Final response, no tool calls
                    messages.append({"role": "assistant", "content": msg.content or ""})
                    print(f"\nAssistant : {msg.content}\n")
                    break

                # The LLM wants to call one or more tools
                messages.append(msg)

                for tool_call in msg.tool_calls:
                    name = tool_call.function.name
                    args = tool_call.function.arguments or {}

                    print(f"  🔧 Appel outil : {name}({args})")
                    clean_args = sanitize_args(name, normalize_args(args), tools_by_name)
                    result = await mcp.call_tool(name, clean_args)

                    # Extraire le texte du résultat
                    tool_output = ""
                    for part in result.content:
                        if isinstance(part, TextContent):
                            tool_output += part.text
                        else:
                            tool_output += json.dumps(part.model_dump())

                    messages.append(
                        {
                            "role": "tool",
                            "content": tool_output,
                        }
                    )


def main() -> None:
    """Console entry point."""
    asyncio.run(run())


if __name__ == "__main__":
    main()
