import asyncio
import json
import ollama
from fastmcp import Client
from mcp.types import TextContent

MODEL = "llama3.2"


def mcp_tools_to_ollama(mcp_tools):
    """Converts MCP tools to Ollama tool format."""
    return [
        {
            "type": "function",
            "function": {
                "name": tool.name,
                "description": tool.description or "",
                "parameters": tool.inputSchema or {"type": "object", "properties": {}},
            },
        }
        for tool in mcp_tools
    ]


def normalize_args(args: dict) -> dict:
    """Fixes malformed arguments generated by some Ollama models that leak
    the JSON schema into values (e.g. {'type': 'string', 'value': '...'})."""
    normalized = {}
    for key, value in args.items():
        if isinstance(value, dict) and "value" in value:
            normalized[key] = value["value"]
        else:
            normalized[key] = value
    return normalized


async def run():
    """Main loop to interact with the user and call MCP tools via Ollama."""
    async with Client("./server.py") as mcp:
        # Connect to the MCP server
        mcp_tools = await mcp.list_tools()
        ollama_tools = mcp_tools_to_ollama(mcp_tools)

        print(f"✅ Serveur MCP connecté — {len(mcp_tools)} outils disponibles")
        print(f"🤖 Modèle : {MODEL}\n")

        messages = [
            {
                "role": "system",
                "content": (
                    "Tu es un assistant de gestion de tâches. "
                    "Utilise les outils disponibles pour répondre aux demandes de l'utilisateur."
                ),
            }
        ]

        # and start the interactive loop
        while True:
            try:
                user_input = input("Vous : ").strip()
            except (KeyboardInterrupt, EOFError):
                print("\nAu revoir !")
                break

            if not user_input or user_input.lower() in ("exit", "quit"):
                break

            messages.append({"role": "user", "content": user_input})

            # Tools calls loop
            while True:
                response = ollama.chat(
                    model=MODEL,
                    messages=messages,
                    tools=ollama_tools,
                )
                msg = response.message

                if not msg.tool_calls:
                    # Final response, no tool calls
                    messages.append({"role": "assistant", "content": msg.content})
                    print(f"\nAssistant : {msg.content}\n")
                    break

                # The LLM wants to call one or more tools
                messages.append(msg)

                for tool_call in msg.tool_calls:
                    name = tool_call.function.name
                    args = tool_call.function.arguments or {}

                    print(f"  🔧 Appel outil : {name}({args})")
                    result = await mcp.call_tool(name, normalize_args(args))

                    # Extraire le texte du résultat
                    tool_output = ""
                    for part in result.content:
                        if isinstance(part, TextContent):
                            tool_output += part.text
                        else:
                            tool_output += json.dumps(part.model_dump())

                    messages.append(
                        {
                            "role": "tool",
                            "content": tool_output,
                        }
                    )


if __name__ == "__main__":
    asyncio.run(run())
